---
version: '3'

includes:
  os-tasks:
    taskfile: ./tasks/Taskfile_{{OS}}.yaml
    dir: ./tasks/

tasks:
  apply:
    desc: Setting up local development environment
    cmds:
      - task: os-tasks:normalize
      - task: os-tasks:git
      - task: os-tasks:direnv
      - task: os-tasks:docker
      - task: os-tasks:editorconfig
      - task: os-tasks:google-cloud-sdk
