---
version: '3'

includes:
  os-tasks:
    taskfile: ./tasks/Taskfile_{{OS}}.yaml
    dir: ./tasks/

tasks:
  apply:
    desc: Setting up local development environment
    cmds:
      - task: os-tasks:normalize
      - task: os-tasks:tools
      - task: os-tasks:docker
      - task: os-tasks:google-cloud-sdk
      - task: os-tasks:vscode
      - task: os-tasks:dotfiles

  dotfiles:
    desc: Apply only dotfiles for test
    cmds:
      - task: os-tasks:dotfiles

  vscode:
    desc: Apply only vscode for test
    cmds:
      - task: os-tasks:vscode

  font:
    decs: Install Hack Gen Nerd font
    cmds:
      - task: os-tasks:font
