version: '3'

tasks:
  brewinstall:
    desc: Install packages
    label: '{{.TASK}}{{if .NAME}} - {{.NAME}}{{end}}'
    vars:
      BREW_FLAGS: '{{default "--formula" .BREW_FLAGS}}'
      CHECK:
        sh: brew list {{.BREW_FLAGS}} '{{.NAME}}' || echo ''
    cmds:
      - brew install {{.BREW_FLAGS}} '{{.NAME}}'
    status:
      - test -n '{{.CHECK}}'

  normalize:
    desc: Use GNU commands
    cmds:
      - task: brewinstall
        vars: { NAME: coreutils }
      - task: brewinstall
        vars: { NAME: diffutils }
      - task: brewinstall
        vars: { NAME: ed }
      - task: brewinstall
        vars: { NAME: findutils }
      - task: brewinstall
        vars: { NAME: gawk }
      - task: brewinstall
        vars: { NAME: gnu-sed }
      - task: brewinstall
        vars: { NAME: gnu-tar }
      - task: brewinstall
        vars: { NAME: grep }
      - task: brewinstall
        vars: { NAME: gzip }

  git:
    cmds:
      - task: brewinstall
        vars: { NAME: git }

  direnv:
    cmds:
      - task: brewinstall
        vars: { NAME: direnv }

  docker:
    cmds:
      - task: brewinstall
        vars: { NAME: docker, BREW_FLAGS: '--cask' }
      - |
        if [[ ! -d ~/.docker ]]; then
          open -a Docker
        fi

  editorconfig:
    cmds:
      - cp -fP ../dotfiles/editorconfig ~/.editorconfig

  google-cloud-sdk:
    cmds:
      - task: brewinstall
        vars: { NAME: google-cloud-sdk, BREW_FLAGS: '--cask' }

  dotfiles:
    cmds:
      - |
        mkdir -p ~/local/devenv/
        cp -rfP ../dotfiles ~/
        ln -sf ~/dotfiles/apply.sh ~/local/devenv/apply.sh
        ln -sf ~/dotfiles/.zshenv ~/.zshenv
        ln -sf ~/dotfiles/.zsh ~/
