[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/lua/plugins/iceberg.lua
'''

[[plugins]]
repo = 'shaunsingh/nord.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/nord.lua
'''

[[plugins]]
repo = 'lukas-reineke/headlines.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/headlines.lua
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/lualine.lua
'''

[[plugins]]
repo = 'sidebar-nvim/sidebar.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/sidebar.lua
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
source ~/.config/nvim/lua/plugins/nerdcommenter.lua
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/lua/plugins/gitgutter.lua
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/.config/nvim/lua/plugins/fugitive.lua
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
source ~/.config/nvim/lua/plugins/treesitter.lua
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/telescope.lua
'''
depends = ['plenary.nvim']

[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/mason.lua
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/mason-lsp.lua
'''
depends = ['mason.nvim', 'cmp-path', 'cmp-buffer', 'cmp-cmdline']

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
source ~/.config/nvim/lua/plugins/lsp.lua
'''
depends = ['mason.nvim']

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
hook_add = '''
source ~/.config/nvim/lua/plugins/nvim-cmp.lua
'''
depends = ['mason.nvim']

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
hook_add = '''
source ~/.config/nvim/lua/plugins/cmp-nvim-lsp.lua
'''
depends = ['mason.nvim']

[[plugins]]
repo = 'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'

[[plugins]]
repo = 'saadparwaiz1/cmp_luasnip'
depends = ['LuaSnip']

[[plugins]]
repo = 'L3MON4D3/LuaSnip'
hook_add = '''
source ~/.config/nvim/lua/plugins/luasnip.lua
'''

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
depends = ['LuaSnip']

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/term.lua
'''

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
hook_add = '''
source ~/.config/nvim/lua/plugins/autotag.lua
'''
