[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/lua/plugins/iceberg.lua
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
source ~/.config/nvim/lua/plugins/nerdcommenter.lua
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/lua/plugins/gitgutter.lua
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/.config/nvim/lua/plugins/fugitive.lua
'''
