[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/lua/plugins/iceberg.lua
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
source ~/.config/nvim/lua/plugins/nerdcommenter.lua
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/lua/plugins/gitgutter.lua
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/.config/nvim/lua/plugins/fugitive.lua
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
source ~/.config/nvim/lua/plugins/treesitter.lua
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
source ~/.config/nvim/lua/plugins/telescope.lua
'''
depends = ['plenary.nvim']

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
source ~/.config/nvim/lua/plugins/lsp.lua
'''

#[[plugins]]
#repo = 'hrsh7th/vim-vsnip'
#hook_add = '''
#source ~/.config/nvim/lua/plugins/vsnip.lua
#'''
#
#[[plugins]]
#repo = 'hrsh7th/vim-vsnip-integ'
#depends = ['vim-vsnip']

[[plugins]]
repo = 'L3MON4D3/LuaSnip'
hook_add = '''
source ~/.config/nvim/lua/plugins/luasnip.lua
'''
